# Generated by Django 4.2.27 on 2026-01-21 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceRecording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("audio_file", models.FileField(upload_to="recordings/%Y/%m/%d/")),
                (
                    "duration",
                    models.FloatField(
                        blank=True, help_text="Duration in seconds", null=True
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pitch_mean",
                    models.FloatField(
                        blank=True, help_text="Mean pitch in Hz", null=True
                    ),
                ),
                (
                    "pitch_std",
                    models.FloatField(
                        blank=True, help_text="Pitch standard deviation", null=True
                    ),
                ),
                (
                    "intensity_mean",
                    models.FloatField(
                        blank=True, help_text="Mean intensity/volume", null=True
                    ),
                ),
                (
                    "intensity_std",
                    models.FloatField(
                        blank=True, help_text="Intensity standard deviation", null=True
                    ),
                ),
                (
                    "speech_rate",
                    models.FloatField(
                        blank=True, help_text="Words per minute", null=True
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional audio features"
                    ),
                ),
                (
                    "insights",
                    models.TextField(
                        blank=True, help_text="AI-generated analysis and insights"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "processing_time",
                    models.FloatField(
                        blank=True, help_text="Processing time in seconds", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "recording",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="api.voicerecording",
                    ),
                ),
            ],
            options={
                "ordering": ["-processed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="voicerecording",
            index=models.Index(
                fields=["-created_at"], name="api_voicere_created_2625c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voicerecording",
            index=models.Index(
                fields=["user", "-created_at"], name="api_voicere_user_id_dff5cd_idx"
            ),
        ),
    ]
